### ISSUE TITLE
Add Clippy as a dev-dependency

### ISSUE THREAD

**Issue by SeanPrashad** [0xazure/supernova#1]
[Clippy](https://crates.io/crates/clippy) is quoted as `A collection of lints to catch common mistakes and improve your Rust code`. Essentially, this tool will help us write better, more concise Rust across the board!

A full list of all linting rules for Clippy can be found [here](https://rust-lang-nursery.github.io/rust-clippy/master/index.html).

Note that docs say [**not to add Clippy as a hard dependency**](https://github.com/rust-lang-nursery/rust-clippy#usage), but to `include it as an optional dependency, as a cargo subcommand, or as an included feature during build`.

**Comment by 0xazure** [comment]
Closing, [see my comment](https://github.com/0xazure/supernova/pull/6#issuecomment-434928267) on #6.
