### ISSUE TITLE
Publish Supernova on Crates.io

### ISSUE THREAD

**Issue by SeanPrashad** [0xazure/supernova#2]
It would be great if we could publish Supernova on [Crates.io](https://crates.io/), the place where Rust's packages live.

Instructions on how to do so can be found [here](https://doc.rust-lang.org/cargo/reference/publishing.html).

**Comment by 0xazure** [comment]
I've been thinking about this a lot and I don't think we'll start publishing on crates.io just yet.

Now that #18 is merged we have automated generation of build artifacts for a variety of platforms, and these artifacts can be distributed and repackaged in a variety of way including as a [Homebrew formula](https://docs.brew.sh/Formula-Cookbook). These artifacts give us a lot more flexibility than publishing on crates.io in terms of distribution, and publishing somewhere else means one more thing to manage.

We may revisit this in the future, but for now I'm going to close this.
