### ISSUE TITLE
Do not run clippy on beta toolchain

### ISSUE THREAD

**Issue by 0xazure** [0xazure/supernova#25]
Our builds have been failing on `beta` with the changes in #24. Some investigation and [reaching out to our friends in #rust](https://github.com/0xazure/supernova/pull/24#issuecomment-437530272) has resulted in the recommendation to only run `clippy` against `stable`.

Since `nightly` is allowed to fail, I'd also like to continue to run `clippy` on this toolchain so we can get a preview of what's coming down the release pipeline.

**Comment by SeanPrashad** [comment]
Yeah, let me at it! 👊🏽
