### ISSUE TITLE
Create guidelines for contributing to Supernova

### ISSUE THREAD

**Issue by SeanPrashad** [0xazure/supernova#7]
Prefixing commit messages and PR's with `feat`, `doc` etc will help maintainers to identify what a commit was intended to change.

Getting started on a `CONTRIBUTING.md` with proper guidelines to follow would be great!

We can take inspiration from [Rust's own `CONTRIBUTING.md`](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md), [Rustfmt's `CONTRIBUTING.md`](https://github.com/rust-lang-nursery/rustfmt/blob/master/Contributing.md) or [Rust-Cookbook's `CONTRIBUTING.md`](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md).

**Comment by 0xazure** [comment]
I need to figure out where I picked up the message prefixes from, I think it would make a good addition to `CONTRIBUTING.md` and would help newcomers understand the reasoning behind it.

I'd also like to add [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) as an additional resource for reference.

Definitely want to draw inspiration from existing `CONTRIBUTING.md`s, no sense in reinventing the wheel when there's so much goodness out there, and thanks for pulling together that list for inspiration!
